
require('./assets/3.16小游戏/command_TypeScript/exit');
require('./assets/3.16小游戏/command_TypeScript/level1/enemy');
require('./assets/3.16小游戏/command_TypeScript/level1/leftToRight');
require('./assets/3.16小游戏/command_TypeScript/level1/mian');
require('./assets/3.16小游戏/command_TypeScript/level2/enemy - 001');
require('./assets/3.16小游戏/command_TypeScript/level2/enemy - 002');
require('./assets/3.16小游戏/command_TypeScript/level2/enemy - 003');
require('./assets/3.16小游戏/command_TypeScript/level2/left');
require('./assets/3.16小游戏/command_TypeScript/level2/main');
require('./assets/3.16小游戏/command_TypeScript/level3/gloabl');
require('./assets/3.16小游戏/command_TypeScript/level3/main - 001');
require('./assets/3.16小游戏/command_TypeScript/level3/right');
require('./assets/3.16小游戏/command_TypeScript/level4/enemy1');
require('./assets/3.16小游戏/command_TypeScript/level4/enemy2');
require('./assets/3.16小游戏/command_TypeScript/level4/enemy3');
require('./assets/3.16小游戏/command_TypeScript/level4/global');
require('./assets/3.16小游戏/command_TypeScript/level4/main - 002');
require('./assets/3.16小游戏/command_TypeScript/level5/global - 001');
require('./assets/3.16小游戏/command_TypeScript/level5/left - 001');
require('./assets/3.16小游戏/command_TypeScript/level5/right - 001');
require('./assets/3.16小游戏/command_TypeScript/level6/global - 002');
require('./assets/3.16小游戏/command_TypeScript/level6/left - 002');
require('./assets/3.16小游戏/command_TypeScript/level6/right1');
require('./assets/3.16小游戏/command_TypeScript/level6/right2');
require('./assets/3.16小游戏/command_TypeScript/level6/right3');
require('./assets/3.16小游戏/command_TypeScript/level7/global - 003');
require('./assets/3.16小游戏/command_TypeScript/level7/left - 003');
require('./assets/3.16小游戏/command_TypeScript/level7/right1 - 001');
require('./assets/3.16小游戏/command_TypeScript/level7/right2 - 001');
require('./assets/3.16小游戏/command_TypeScript/level7/right3 - 001');
require('./assets/3.16小游戏/command_TypeScript/level8/global - 004');
require('./assets/3.16小游戏/command_TypeScript/level8/left - 004');
require('./assets/3.16小游戏/command_TypeScript/level8/right - 002');
